### ISSUE TITLE
1.0.13 Bitcode issue

### ISSUE THREAD

**Issue by Kamilton** [PayU-EMEA/PayU-iOS#7]
I've updated SDK using Cocapods 1.0.10 -> 1.0.13

After update I can't build my solution. I get error '/**/XCFrameworkIntermediates/PayULite/PayU_SDK_Lite.framework/PayU_SDK_Lite' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '**/PayULite/PayU_SDK_Lite.framework/PayU_SDK_Lite' for architecture arm64

Bitcode for this framework is set enabled

Everything worked well with version 1.0.10, and nothing else was changed

**Comment by twprzybysz** [comment]
@Kamilton this looks like https://github.com/PayU-EMEA/PayU-iOS/issues/6 - someone used new toolchain to prepare the package without noticing that Bitcode is disabled by default (https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes).
cc @aivashyna

**Comment by aivashyna** [comment]
@twprzybysz 
@Kamilton 

Thanks for letting us know.
We will take a look on this in the nearest few days and let you know with the update.

**Comment by Kamilton** [comment]
Disabled bitcode for my project, now issue doesn't appear. Closing this as copy to #6
